### ISSUE TITLE
Add a check before the ansible installation that checks the vars.yaml parameters

### ISSUE THREAD

**Issue by sradco** [ViaQ/Main#11]
Since the openshift ansible takes a long time, Please add a check before the ansible installation that validates the vars.yaml parameters.

After a very very long run the ansible failed with this error:

TASK [openshift_logging_mux : Add mux namespaces] ********************************************************************************************************************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_logging_mux/tasks/main.yaml:202
fatal: [localhost]: FAILED! => {
"failed": true
}

MSG:

Unexpected templating type error occurred on ({{ openshift_logging_mux_namespaces | union(openshift_logging_mux_default_namespaces) }}): coercing to Unicode: need string or buffer, list found

to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/byo/config.retry
PLAY RECAP ***********************************************************************************************************************************************************************************
localhost : ok=713 changed=109 unreachable=0 failed=1

Failure summary:

Host: localhost
Play: Create Hosted Resources
Task: openshift_logging_mux : Add mux namespaces
Message: Unexpected templating type error occurred on ({{ openshift_logging_mux_namespaces | union(openshift_logging_mux_default_namespaces) }}): coercing to Unicode: need string or buffer, list found

**Comment by richm** [comment]
closing here - moved to https://github.com/openshift/openshift-ansible/issues/5022
