### ISSUE TITLE
Running OpenShift Origin installation playbooks enables it own software repo

### ISSUE THREAD

**Issue by mmmmmmpc** [ViaQ/Main#14]
When running the Ansible playbooks for Origin, the following file is deployed:
/etc/yum.repos.d/CentOS-OpenShift-Origin.repo

... in it the following repo is enabled:
[centos-openshift-origin]
name=CentOS OpenShift Origin
baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-PaaS

which has the version 3.6 instead 1.5 not letting the user choose the version to be installed.

**Comment by richm** [comment]
there is a way to specify the origin package versions
set `openshift_pkg_version=-1.5.0`
you can set something like that in the inventory file - in vars.yaml, use `openshift_pkg_version: "-1.5.0"` or on the command line like `-e openshift_pkg_version=-1.5.0`

**Comment by mmmmmmpc** [comment]
This is a very nice way to ensure that the openshift package is 1.5.0.
The issue is that the system ends up with two OpenShift Origin repos and that, in some cases, it won't use the expected packages leading to a failed install.

**Comment by richm** [comment]
ok - if you submit a pr for this I will merge it

**Comment by mmmmmmpc** [comment]
I tried adding ```openshift_pkg_version: "-1.5.0"``` in ```vars.yaml```, and it installed OpenShift Origin 1.5.0.
When running ```yum update``` it tries to update to 3.6 because the repo is configured for ```lastest```.
In any case, it is a good idea to add it as a commented example in ```vars.yaml```.
Submitted a PR https://github.com/ViaQ/Main/pull/18

**Comment by mmmmmmpc** [comment]
Submitted a PR for the right branch and got merged: https://github.com/ViaQ/Main/pull/20
Closing this
