### ISSUE TITLE
When installing on centos there are missing dependencies

### ISSUE THREAD

**Issue by sradco** [ViaQ/Main#39]
I tried installing OpenShift 3.11 based on the README with Centos, but there are missing dependencies:

Error: Package: origin-sdn-ovs-3.11.0-1.el7.git.0.62803d0.x86_64 (centos-openshift-origin311)
           Requires: openvswitch >= 2.6.1
           Available: openvswitch-2.0.0-7.el7.x86_64 (base)
               openvswitch = 2.0.0-7.el7

@richm

**Comment by richm** [comment]
looks like the ovs requirement was dropped - https://github.com/ViaQ/Main/commit/3088939e81c4d129169bc441ece18a7812d1f3fb
