### ISSUE TITLE
Error after deployment:  Discover: [security_exception] no permissions for indices:data/read/field_stats

### ISSUE THREAD

**Issue by StLuke** [ViaQ/Main#6]
This error pops up after clean deployment
Discover: [security_exception] no permissions for indices:data/read/field_stats

Getting more info:
Error: [security_exception] no permissions for indices:data/read/field_stats
ErrorAbstract@https://kibana.example.com/bundles/commons.bundle.js?v=10229:95501:20
StatusCodeError@https://kibana.example.com/bundles/commons.bundle.js?v=10229:95663:6
respond@https://kibana.example.com/bundles/commons.bundle.js?v=10229:96868:16
checkRespForFailure@https://kibana.example.com/bundles/commons.bundle.js?v=10229:96831:8
[24]</AngularConnector.prototype.request/<@https://kibana.example.com/bundles/commons.bundle.js?v=10229:95449:8
processQueue@https://kibana.example.com/bundles/commons.bundle.js?v=10229:42452:29
scheduleProcessQueue/<@https://kibana.example.com/bundles/commons.bundle.js?v=10229:42468:28
$eval@https://kibana.example.com/bundles/commons.bundle.js?v=10229:43696:17
$digest@https://kibana.example.com/bundles/commons.bundle.js?v=10229:43507:16
$apply@https://kibana.example.com/bundles/commons.bundle.js?v=10229:43804:14
done@https://kibana.example.com/bundles/commons.bundle.js?v=10229:38253:37
completeRequest@https://kibana.example.com/bundles/commons.bundle.js?v=10229:38451:8
requestLoaded@https://kibana.example.com/bundles/commons.bundle.js?v=10229:38392:10

Not sure if its related to this, but kibana seems to be searching for samples endlessly.

**Comment by StLuke** [comment]
This seems to be solved by adding permissions for admin to use kibana

oc project logging
oc login --username=admin --password=admin
oc login --username=system:admin
oadm policy add-cluster-role-to-user cluster-admin admin

**Comment by richm** [comment]
Right, as documented here: https://github.com/ViaQ/Main/blob/master/README-mux.md#running-kibana
